launchfile:
  fleet_size: 5
  codes:
    - 4001
    - 4242
    - 4242
    - 4007
    - 6012
  models:
    - 'x500'
    - 'X3'
    - 'X3'
    - 'emesent_hovermap'
    - 'typhoon_h480'
  xs:
    - -1
    - -13.5
    - -13.5
    - -1
    - 0
  ys:
    - 6.5
    - -6.5
    - 6.5
    - -6.5
    - -0.5
  world: 'tugbot_depot'
