bool presence
bool takeoff
bool landing
bool retrieval
bool dropoff
float32 x
float32 y
float32 z
---
int64 leader_id
bool present
bool taking_off
bool landing
bool retrieval
bool dropoff
bool success
